#!/usr/bin/env python3
"""Generate the WordPress homepage stylesheet from the static one.

    python3 tools/gen-home-css.py

Reads  Website Redesign/website/css/style.css
Writes Website Redesign/wordpress/bb-features/assets/css/home.css

The sibling of gen-module-css.py, and the same bargain: the WP sheet is derived
rather than maintained, so it and the static build cannot drift. The transform
is the same one, read that file for the reasoning behind each step. What is
specific to the homepage:

  * the prefix is `bbh-` and the page prefix dropped is `hp-`, so `.hp-hero`
    becomes `.bbh-hero`; tokens are declared on `.bbh`, the class every
    pattern's root group carries;

  * only the shared foundation the homepage actually uses is carried over —
    tokens, reset, type scale, `.tag`, `.btn`, `.checks`, the app band, the two
    reviewer type rules, the scroll animations, the icon metrics and the module
    pages' testimonial masonry — plus the whole generated homepage block. The
    Features page's own sections are dropped;

  * dropping `hp-` means a shared class can COLLIDE with a homepage one: the
    Features hero is `.hero` and the homepage's is `.hp-hero`, and both land on
    `.bbh-hero`. That is why the slices below are narrow, and why
    check_collisions() fails the build rather than letting one quietly win —
    `.review`, `.split`, `.integrations` and `.testimonials` all collide too;

  * the icon metrics are scoped with `:where(.bbh)`, which adds no specificity,
    so `img[src$="check.svg"]` keeps losing to `.checks li img` exactly as it
    does in the static cascade. Scoping them with a plain `.bbh` would flip
    that pair and several others;

  * a WORDPRESS SHIM is appended that the static sheet has no need of, because
    core blocks bring markup the design never had: a buttons wrapper that eats
    a flex gap, an image figure the design's border-radius lands on instead of
    the picture, and a section root that — carrying the body rule's background
    — hides any `z-index: -1` pseudo-element under itself unless it isolates;

  * the page rhythm is the one rule that cannot survive as written. The static
    sheet says `.hp > * + *`, but a pattern has no siblings at author time.
    In the assembled page the section roots ARE siblings and each wears `.bbh`,
    so it becomes `.bbh + :where(.bbh)` — the :where() keeps it weighing one
    class, as `.hp > * + *` does, so a section that overrides its own gap still
    wins on source order.
"""

import re
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / 'website' / 'css' / 'style.css'
OUT = ROOT / 'wordpress' / 'bb-features' / 'assets' / 'css' / 'home.css'

FENCE_OPEN = '/* ============ HOMEPAGE — generated by tools/assemble-home.py ============ */'
FENCE_CLOSE = '/* ============ END HOMEPAGE ============ */'
BANNER = '/* =================================================================\n   '

HEADER = """/* =============================================================
   BB Features — homepage sections
   Built from Figma: BuddyBoss-Website / Home / 3780:57831

   GENERATED — do not edit. Run wordpress/tools/gen-home-css.py after
   changing website/css/style.css (which is itself generated for the
   homepage block — edit website/home-parts/*.css and re-run
   tools/assemble-home.py first).

   Everything is prefixed bbh- and every token is declared on .bbh, so it
   neither reads from nor leaks into the Features or module-page styles.
   ============================================================= */
"""

# (start marker, end marker, banner to write above it). End is exclusive.
KEEP = [
    (':root {', '/* ---------- reset', None),
    ('/* ---------- reset', BANNER + 'HEADER', None),
    (BANNER + 'APP SECTION', BANNER + 'THEME / READYLAUNCH pair', None),
    # Only two rules of the Features BIG REVIEW block are wanted: the homepage's
    # review band writes its own everything else but leans on these two for the
    # reviewer's name and role. Taking the block whole would collide `.review`.
    ('.review__name {', '.review__logo',
     '/* ---------- reviewer credit (from the shared review card) --------- */'),
    ('/* small one-off utilities', BANNER + 'ICON METRICS', None),
    (BANNER + 'ICON METRICS', BANNER + 'RESPONSIVE', None),
    ('/* ---------- testimonial masonry', BANNER + 'SOCIAL GROUPS', None),
    (FENCE_OPEN, FENCE_CLOSE, None),
]

# Classes the theme script owns; they are set on <html> or are the scope class
# itself, so they are never prefixed.
PASSTHROUGH = {'js', 'reveal-all', 'bbh'}

# Element selectors in the reset that need scoping.
ELEMENTS = ['img, svg', 'p, figure, blockquote, dl, dd', 'h1,h2,h3,h4,h5,h6', 'ul', 'a', 'button']

# Applied to the raw slice, before comments are stashed, so a rule and the
# comment explaining it go together.
PRE_EDITS = [
    ("""/* ---------- page rhythm ----------
   Every row of the homepage sits exactly 88px below the one before it — one
   gap, no exceptions, all the way from the hero to the footer. Stating it once
   here means a section that forgets to set its own still lands right; one did,
   and nothing about its own geometry gave that away. */
.hp > * + * { margin-top: 88px; }
/* the footer is a sibling of <main>, not a child, so the rule above cannot
   reach it and it would otherwise fall back to the 80px --section-gap the
   other fifteen pages use */
main.hp + .site-footer { margin-top: 88px; }""",
     """/* ---------- page rhythm ----------
   Every row of the homepage sits exactly 88px below the one before it — one
   gap, no exceptions, from the hero to the last band.

   The static page says `.hp > * + *`, matching on <main>'s children. A block
   pattern has no siblings while it is being authored, so that cannot survive
   the port. What does survive is the assembled page: every section root wears
   .bbh, and in the post content they are each other's siblings — so the same
   single gap is stated as an adjacency between two section roots.

   The target sits in :where() so the rule weighs exactly what it weighs on the
   static page — one class. `.hp > * + *` counts .hp and nothing else, which
   ties it with every per-section `margin-top` and lets source order decide;
   the sections are all declared below it, so a section that sets its own gap
   wins. Written as a bare `.bbh + .bbh` it counts TWO classes, quietly
   outranks all of them, and the one section that overrides the rhythm
   (.bbh-facts drops to 64 under 1024px) never got its 64 back.

   The footer is a template part in WordPress, not a sibling of anything here,
   so the rule that gapped it off <main> is dropped with the footer. */
.bbh + :where(.bbh) { margin-top: 88px; }"""),
    # `overflow-x: hidden` is a document-level guard against a horizontal
    # scrollbar, and harmless on <body>. On a section root it is poison: a box
    # with one axis hidden and the other visible is a scroll container in BOTH,
    # so every root clipped whatever its children were drawn to bleed — the 2px
    # gradient ring under each split card vanished this way, with no box out of
    # place to show it. `clip` is the one value that pairs with `visible`
    # without blockifying the other axis, so the guard survives and the vertical
    # bleed comes back. It stays in the body rule rather than moving to the shim
    # so that the sections which DO clip (the hero, the app band) still override
    # it from their own rules further down the sheet.
    ('  overflow-x: hidden;', '  overflow-x: clip;'),
    # the hero's header overlap is opt-in under WordPress: a WP header lives in
    # the template, and pulling up under an opaque one would hide the headline
    ("""  background: var(--bg-brand-subtle);
  margin-top: calc(-1 * var(--header-h));
  padding-top: var(--header-h);
}""",
     """  background: var(--bg-brand-subtle);
}
/* opt-in: make the header transparent in the parent theme, then add this class
   to the hero group so the peach runs up behind the bar as it does in Figma */
.hp-hero--under-header {
  margin-top: calc(-1 * var(--header-h));
  padding-top: var(--header-h);
}"""),
]

# Rules that only make sense in the static page's document.
DROP = [
    'main > .hero + .section { margin-top: 104px; }',
]

# Shared components that reflow in the Features media queries and that the
# homepage uses. Everything else in that block belongs to sections this sheet
# does not carry — and `.split`, `.review` and `.hero__stage` would collide.
SHARED_RESPONSIVE = ('.app-band__inner',)

# The same again for the module pages' own media queries, which sit after the
# MODULE PAGE block and before the homepage fence. The testimonials band
# borrows that family's review masonry wholesale (.mp-reviews / .mp-rgrid /
# .mp-rcol / .mp-review), and the masonry is the one thing in it that reflows:
# three columns, then two under 1100 and one under 720. Taking only the base
# rules left the homepage stuck at three columns at every width — the band ran
# ~400px taller than the static page below 1100 and nothing above it moved, so
# a section-height check at 1600 could not see it.
MODULE_RESPONSIVE = ('.mp-rgrid',)


# Rules with no counterpart in the static sheet, because they answer to
# Gutenberg's markup rather than the design's. Appended last so they win a tie.
SHIM = """
/* =================================================================
   WORDPRESS SHIM
   The static page has none of this; core blocks do.
   ================================================================= */
/* Every section root carries the page background, because the tokens and the
   body rule are declared on .bbh rather than on :root and <body>. That turns a
   `z-index: -1` pseudo-element into an invisible one: with no stacking context
   between it and the document root, it paints UNDER the section's own white
   fill instead of over it, and the gradient ring around all three split cards
   simply disappears — no box moves, so only a pixel diff finds it. Isolating
   each root restores the static paint order: background, then the negative
   layer, then the content. */
.bbh { isolation: isolate; }

/* core/buttons wraps its buttons in a container div. The static page has the
   two hero buttons as direct children of a flex row with a 24px gap, and that
   wrapper swallows it — the pair lands 20px too close with nothing else out of
   place. `display: contents` takes the wrapper out of the box tree, so every
   button is once again a child of whatever the design put it in, with that
   parent's own gap and alignment. */
.bbh .wp-block-buttons { display: contents; }
.bbh .wp-block-button { margin: 0; }
/* The anchor is only the label here — .bbh-btn styles the block itself, as it
   does everywhere else in this sheet. Reset what wp-block-library and a
   theme.json elements.button rule would otherwise put on it. */
.bbh .wp-block-button__link {
  background: none; border: 0; padding: 0; border-radius: 0; color: inherit;
  font: inherit; letter-spacing: inherit; text-decoration: none;
}
/* The arrow was an <img> inside the anchor. core/button keeps plain text, so
   it is redrawn as a pseudo-element — which also stops an editor deleting it
   by accident. Box and leaf geometry are the ICON METRICS entry for
   arrow-right.svg, unchanged: a 20px box with the leaf at 2.5 / 3.75, and the
   24px box the 56px button draws the same file in. A button that had no icon
   in the design is marked --noicon by gen-patterns.py. */
.bbh-btn::after {
  content: ''; flex: none; width: 20px; height: 20px;
  background: url('../icon/arrow-right.svg') no-repeat 2.5px 3.75px / 15.001px 12.501px;
}
.bbh-btn--lg::after {
  width: 24px; height: 24px;
  background-position: 3px 4.5px; background-size: 18.001px 15.001px;
}
/* the arrow ships brand-coloured; on the brand fill it has to flip to white */
.bbh-btn--solid::after { filter: brightness(0) invert(1); }
.bbh-btn--noicon::after { content: none; }

/* core/image wraps the picture in a <figure> and the design's class lands on
   the wrapper, so a border-radius rounds a box the picture inside it ignores —
   the three reviewer portraits came out square-cornered. Handing the radius
   down is enough; sizing is already right, because the wrapper is what the
   design's width/height rules were written for. */
.bbh .wp-block-image > img { border-radius: inherit; }

/* When the design put no class on the <img>, the figure core adds is a box the
   static page never had, and it lands between a sized wrapper and the picture
   it sizes. `.bbh-split__panel img` and `.bbh-dfy__panel img` both say
   `height: 100%`, and a percentage height resolves against the figure — which
   is auto — instead of against the panel, so five artwork panels fell back to
   their natural aspect and stopped filling (and cropping to) their frame. At
   1600 the frames happen to BE 740x528, the images' own aspect, so nothing
   showed; below 1080 the panel stretches to the card and the picture came up
   short by up to 300px.

   `display: contents` drops the figure out of the box tree, so the picture is
   once again a direct child of the wrapper the design wrote those rules for —
   the same fix, for the same reason, as the core/buttons wrapper above. Only
   the figures with no design class of their own qualify: where the class DID
   land on the figure, that box is the one the design's rules size. */
.bbh .wp-block-image:not([class*="bbh-"]) { display: contents; }
"""


def slice_source(css: str) -> str:
    out = []
    for start, end, note in KEEP:
        i = css.find(start)
        if i < 0:
            sys.exit(f'gen-home-css: marker not found: {start!r}')
        j = css.find(end, i) if end else len(css)
        if end and j < 0:
            sys.exit(f'gen-home-css: end marker not found: {end!r}')
        if note:
            out.append(note)
        out.append(css[i:j].rstrip() + '\n')
    return '\n'.join(out)


def responsive_steps(css: str) -> str:
    """The token steps, plus the shared reflows, out of the Features queries.

    Those queries mostly reflow the Features page and cannot come across whole:
    half their selectors would collide with a homepage class of the same
    stripped name. Only the `:root` declarations and the components in
    SHARED_RESPONSIVE are pulled out. The homepage's own breakpoints ride along
    inside the generated block and need nothing here.
    """
    a = css.index(BANNER + 'RESPONSIVE')
    b = css.index(BANNER + 'MODULE PAGE')
    block = css[a:b]

    out = []
    for m in re.finditer(r'@media \(max-width: (\d+)px\) \{\n(.*?)\n\}\n', block, re.S):
        width, body = m.groups()
        lines = []
        root = re.search(r'^\s*:root \{(.*?)\}', body, re.S | re.M)
        if root:
            decls = ' '.join(l.strip() for l in root.group(1).strip().splitlines())
            lines.append(f'  :root {{ {decls} }}')
        for sel in SHARED_RESPONSIVE:
            r = re.search(r'^\s*%s \{([^}]*)\}' % re.escape(sel), body, re.M)
            if r:
                lines.append('  %s {%s}' % (sel, r.group(1)))
        if lines:
            out.append(f'@media (max-width: {width}px) {{\n' + '\n'.join(lines) + '\n}\n')
    return ''.join(out)


def module_steps(css: str) -> str:
    """The reflows the borrowed module-page components need.

    Same bargain as responsive_steps: the module family's media queries mostly
    reflow sections this sheet does not carry, so only the selectors named in
    MODULE_RESPONSIVE come across. A rule that lists several selectors is
    reduced to the wanted ones — `.mp-rgrid, .gridcards` arrives as `.mp-rgrid`
    alone, because `.gridcards` has nothing to match here.
    """
    a = css.index(BANNER + 'MODULE PAGE')
    b = css.index(FENCE_OPEN)
    block = css[a:b]

    out = []
    for m in re.finditer(r'@media \(max-width: (\d+)px\) \{\n(.*?)\n\}\n', block, re.S):
        width, body = m.groups()
        lines = []
        for r in re.finditer(r'^ *([^{}\n]+?) \{([^{}]*)\}', body, re.M):
            keep = [p.strip() for p in r.group(1).split(',')
                    if p.strip() in MODULE_RESPONSIVE]
            if keep:
                lines.append('  %s {%s}' % (', '.join(keep), r.group(2)))
        if lines:
            out.append(f'@media (max-width: {width}px) {{\n' + '\n'.join(lines) + '\n}\n')
    if not out:
        sys.exit('gen-home-css: no module reflows matched %s — check MODULE_RESPONSIVE'
                 % ', '.join(MODULE_RESPONSIVE))
    return ''.join(out)


def pre_process(css: str) -> str:
    """Edits made on the raw slice, before comments are stashed, so that a rule
    and the comment explaining it can be rewritten or dropped together."""
    for old, new in PRE_EDITS:
        css = css.replace(old, new)
    for dead in DROP:
        css = css.replace(dead + '\n', '')
    return css


def transform(css: str) -> str:
    # Comments are full of `--------` rules and `.class` mentions; hide them
    # so neither substitution below can chew through a banner.
    comments: list[str] = []

    def stash(m):
        comments.append(m.group(0))
        return '\x00%d\x00' % (len(comments) - 1)

    css = re.sub(r'/\*.*?\*/', stash, css, flags=re.S)

    # Quoted strings need the same protection, and for the same reason: the
    # icon metrics match on `img[src$=".svg"]`, and the class substitution
    # below is happy to read that `.svg` as a class and rename it. It also
    # holds the font stack, where 'Segoe UI' has no business being touched.
    strings: list[str] = []

    def stash_str(m):
        strings.append(m.group(0))
        return '\x01%d\x01' % (len(strings) - 1)

    css = re.sub(r'"[^"]*"|\'[^\']*\'', stash_str, css)

    # --- custom properties -------------------------------------------------
    css = re.sub(r'(?<![\w-])--(?!bbh-)([a-z0-9-]+)', r'--bbh-\1', css)

    # --- classes -----------------------------------------------------------
    def cls(m):
        name = m.group(1)
        if name in PASSTHROUGH or name.startswith(('bbh-', 'wp-', 'is-')):
            return '.' + name
        if name.startswith('hp-'):
            return '.bbh-' + name[3:]
        return '.bbh-' + name
    css = re.sub(r'\.([a-zA-Z][\w-]*)', cls, css)

    # a bare `.hp` was the page scope; under WP the pattern root carries .bbh
    css = re.sub(r'\.bbh-hp(?=[\s.:,{])', '.bbh', css)

    # --- roots -------------------------------------------------------------
    css = css.replace(':root {', '.bbh {')
    css = re.sub(r'^body \{', '.bbh {', css, flags=re.M)
    css = css.replace('*, *::before, *::after { box-sizing: border-box; }',
                      '.bbh, .bbh *, .bbh *::before, .bbh *::after { box-sizing: border-box; }')
    # the html rule is document-level; a block pattern has no business setting it
    css = re.sub(r'^html \{[^}]*\}\n', '', css, flags=re.M)
    css = re.sub(r'^ +html \{[^}]*\}\n', '', css, flags=re.M)

    # --- reset element selectors ------------------------------------------
    for sel in ELEMENTS:
        css = re.sub(r'^%s (?=\{)' % re.escape(sel), '.bbh :where(%s) ' % sel, css, flags=re.M)
    css = re.sub(r'^:focus-visible ', '.bbh :focus-visible ', css, flags=re.M)

    # --- icon metrics ------------------------------------------------------
    # `:where()` scopes them without adding specificity, so every icon rule
    # keeps the (0,1,1) it has in the static sheet and loses to the component
    # rules that size the same images — which is the order the page is built on.
    css = re.sub(r'^img\[', ':where(.bbh) img[', css, flags=re.M)

    css = re.sub(r'\x01(\d+)\x01', lambda m: strings[int(m.group(1))], css)

    # --- restore comments, with their own class references renamed ---------
    def restore(m):
        c = comments[int(m.group(1))]
        c = re.sub(r'\.hp-([a-z][\w-]*)', r'.bbh-\1', c)
        c = re.sub(r'(?<![\w-])--(?![-\s])(?!bbh-)([a-z][\w-]*)', r'--bbh-\1', c)
        return c

    return re.sub(r'\x00(\d+)\x00', restore, css)


def check_collisions(sliced: str) -> None:
    """Fail if a kept shared class would land on a homepage class's name.

    `hp-` is stripped, so `.hp-review` and the Features `.review` both become
    `.bbh-review`. Source order would decide the winner silently and the
    geometry probe would only report that some band is the wrong height.
    """
    i = sliced.index(FENCE_OPEN)
    shared, fence = sliced[:i], sliced[i:]
    strip = lambda s: re.sub(r'/\*.*?\*/', '', s, flags=re.S)
    own = {m.group(1)[3:] for m in re.finditer(r'\.(hp-[\w-]*)', strip(fence))}
    have = {m.group(1) for m in re.finditer(r'\.([a-zA-Z][\w-]*)', strip(shared))}
    clash = sorted(own & have)
    if clash:
        sys.exit('gen-home-css: shared classes collide with homepage ones once '
                 '`hp-` is stripped — narrow the KEEP slices: ' + ', '.join(clash))


def main() -> None:
    css = SRC.read_text()
    sliced = pre_process(slice_source(css))
    check_collisions(sliced)

    body = transform(sliced)
    steps = transform(responsive_steps(css))
    borrowed = transform(module_steps(css))
    OUT.write_text(HEADER + body.rstrip() + '\n\n'
                   '/* ---------- token steps ------------------------------------------ */\n'
                   + steps.rstrip() + '\n\n'
                   '/* ---------- reflows for the borrowed module components ------------ */\n'
                   + borrowed.rstrip() + '\n' + SHIM)

    # Sanity checks — a silent bad substitution here is expensive to find later.
    text = re.sub(r'/\*.*?\*/', '', OUT.read_text(), flags=re.S)
    problems = []
    if '.bbh-bbh' in text:
        problems.append('double-prefixed class (.bbh-bbh)')
    if re.search(r'(?<![\w-])--(?!bbh-)[a-z]', text):
        problems.append('unprefixed custom property')
    stray = {m.group(1) for m in re.finditer(r'^\s*\.([a-z][\w-]*)', text, re.M)
             if m.group(1) not in PASSTHROUGH and not m.group(1).startswith(('bbh', 'is-'))}
    if stray:
        problems.append('unprefixed classes: ' + ', '.join(sorted(stray)))
    if re.search(r'^(img|html|body|:root)\b', text, re.M):
        problems.append('unscoped element or document selector')
    if text.count('{') != text.count('}'):
        problems.append('unbalanced braces')
    if problems:
        sys.exit('gen-home-css: ' + '; '.join(problems))
    print(f'wrote {OUT.relative_to(ROOT)} ({len(text.splitlines())} lines)')


if __name__ == '__main__':
    main()
