#!/usr/bin/env python3
"""Assemble website/home.html and its stylesheet block from website/home-parts/.

    python3 tools/assemble-home.py

Each homepage section is built in isolation as a pair of files under
`website/home-parts/` — `NN-slug.html` (the fragment) and `NN-slug.css` (only
what that section adds). This walks them in numeric order and produces:

  * `website/home.html`  — head + the shared header + <main class="hp"> + every
    fragment in order + the footer + the shared scripts
  * a fenced block inside `website/css/style.css`, rewritten in place, holding
    every part's CSS in the same order

Keeping the parts separate is what lets sections be built and re-verified one
at a time without agents colliding in one file; keeping assembly generated is
what stops home.html and the parts drifting apart. Re-run it after any edit to
a part — never hand-edit home.html or the fenced CSS block.

The header and the footer both come from index.html rather than from a part —
they are shared components that every page carries, so a homepage-local copy
would be one more thing to keep in sync.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SITE = ROOT / 'website'
PARTS = SITE / 'home-parts'

FENCE_OPEN = '/* ============ HOMEPAGE — generated by tools/assemble-home.py ============ */'
FENCE_CLOSE = '/* ============ END HOMEPAGE ============ */'

HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>BuddyBoss — Your full-scale community and online learning platform</title>
<meta name="description" content="Build online communities, membership sites and social learning platforms on your own WordPress site — with profiles, groups, forums, activity feeds, messaging, courses and a branded mobile app.">
<link rel="icon" href="assets/icon/logo-buddyboss.svg">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="css/style.css">
<script>document.documentElement.classList.add('js');</script>
</head>
<body>
"""


def slab(path: pathlib.Path) -> str:
    return path.read_text().strip('\n')


def between(text: str, start_pat: str, end_pat: str) -> str:
    """The slice from `start_pat` to the first `end_pat` AFTER it.

    Searching for the end from position 0 works for the header and the footer,
    whose closing tags are unique, and silently fails for the script tag: the
    first `</script>` in index.html closes the inline `js`-class snippet up in
    the <head>, so the slice ran backwards and came out empty. The homepage
    shipped with no main.js at all — which sets `js` on <html> but never adds
    `is-visible`, leaving every .reveal and .stagger section at opacity 0 for
    good, and the nav dropdowns and stat counters dead with them."""
    a = re.search(start_pat, text)
    b = re.search(end_pat, text[a.end():]) if a else None
    if not a or not b:
        sys.exit(f'assemble-home: could not find {start_pat!r}..{end_pat!r} in index.html')
    return text[a.start():a.end() + b.end()]


def main() -> None:
    index = (SITE / 'index.html').read_text()
    header = between(index, r'<header class="site-header"', r'</header>')
    footer = between(index, r'<footer class="site-footer"', r'</footer>')
    scripts = between(index, r'<script src="js/main\.js"', r'</script>')

    frags = sorted(PARTS.glob('[0-9][0-9]-*.html'))
    if not frags:
        sys.exit('assemble-home: no parts built yet')

    body_parts = frags

    out = [HEAD, header, '', '<main class="hp">']
    for f in body_parts:
        out.append(f'\n<!-- {"=" * 18} {f.stem.upper()} {"=" * 18} -->')
        out.append(slab(f))
    out.append('\n</main>\n')
    out.append(footer)
    out.append('')
    out.append(scripts)
    out.append('</body>\n</html>')
    (SITE / 'home.html').write_text('\n'.join(out) + '\n')

    # --- the stylesheet block ------------------------------------------
    css_parts = []
    for f in frags:
        p = f.with_suffix('.css')
        if p.is_file() and p.read_text().strip():
            css_parts.append(f'\n/* ---------- {f.stem} ---------- */\n' + slab(p))
    rhythm = """
/* ---------- page rhythm ----------
   Every row of the homepage sits exactly 88px below the one before it — one
   gap, no exceptions, all the way from the hero to the footer. Stating it once
   here means a section that forgets to set its own still lands right; one did,
   and nothing about its own geometry gave that away. */
.hp > * + * { margin-top: 88px; }
/* the footer is a sibling of <main>, not a child, so the rule above cannot
   reach it and it would otherwise fall back to the 80px --section-gap the
   other fifteen pages use */
main.hp + .site-footer { margin-top: 88px; }"""
    block = FENCE_OPEN + '\n' + rhythm + '\n' + '\n'.join(css_parts) + '\n' + FENCE_CLOSE

    style_path = SITE / 'css' / 'style.css'
    style = style_path.read_text()
    if FENCE_OPEN in style:
        style = re.sub(re.escape(FENCE_OPEN) + r'.*?' + re.escape(FENCE_CLOSE),
                       lambda _: block, style, flags=re.S)
    else:
        style = style.rstrip('\n') + '\n\n' + block + '\n'
    style_path.write_text(style)

    print(f'home.html: {len(body_parts)} sections in <main>, shared header + footer')
    for f in frags:
        has = 'css' if f.with_suffix('.css').is_file() else '   '
        print(f'   {f.stem:22} {has}')


if __name__ == '__main__':
    main()
